# Generated by Django 4.2.6 on 2024-01-31 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=100, unique=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('whitelisted_ips', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('who', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=200)),
                ('what', models.CharField(max_length=500, null=True)),
                ('where', models.CharField(max_length=100)),
                ('share_name', models.CharField(max_length=100, null=True)),
                ('object_type', models.CharField(max_length=100)),
                ('host', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('old_path', models.CharField(max_length=500, null=True)),
                ('new_path', models.CharField(max_length=500, null=True)),
                ('old_owner', models.CharField(max_length=500, null=True)),
                ('new_owner', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
