# Generated by Django 4.2.6 on 2024-01-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apitoken',
            name='whitelisted_ips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
