# Generated by Django 4.2.6 on 2024-02-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_apitoken_whitelisted_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='logentry',
            name='new_acl',
            field=models.CharField(max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='logentry',
            name='old_acl',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
